version: '3'

includes:
  common: ./common.yml
  config: ./conf.vars.yml

tasks:

  default:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  close_server:
    vars:
      ins_name: gost_server
    cmds:
      - '{{.runcmd}} rm -f {{.ins_name}}'

  close_client:
    vars:
      ins_name: gost_client
    cmds:
      - '{{.runcmd}} rm -f {{.ins_name}}'

  close:
    deps:
      - close_server
      - close_client

  server:
    vars:
      ins_name: gost_server
    cmds:
      - task: close_server
      - task: common:server
        vars:
          runner:
            '
              {{.runcmd}} run
                {{.runner_option}}
                --name {{.ins_name}}
                -p {{.kcp_port}}:{{.kcp_port}}/udp
                -p {{.tcp_port}}:{{.tcp_port}}
                mooxe/gogost gost
            '

  client_in:
    deps:
      - task: common:client_unkcp
        vars:
          runner: gost
      - task: common:client_proxy
        vars:
          runner: gost

  client:
    vars:
      ins_name: gost_client
    cmds:
      - task: close_client
      - '
        {{.runcmd}} run
          {{.runner_option}}
          --name {{.ins_name}}
          -v $(pwd)/tasks:/root/tasks
          -p {{.proxy_port}}:{{.proxy_port}}
          mooxe/gogost task -t ./tasks/remote.yml client_in
        '
