version: '3'

includes:
  common: ./common.yml
  config: ./conf.vars.yml

tasks:

  help: task --list-all
  default:
    - task: help

  server:
    cmds:
      - task: common:server

  client_unkcp:
    cmds:
      - task: common:client_unkcp

  client_proxy:
    cmds:
      - task: common:client_proxy

  client:
    deps:
      - client_unkcp
      - client_proxy

  curltest:
    - task: common:curltest
      vars:
        ip_host: cip.cc
    - task: common:curltest
      vars:
        ip_host: ipinfo.io
