version: '3'

vars:
  docker_name: gogost
  image_name: mooxe/{{.docker_name}}

tasks:

  help: task --list-all
  default:
    - task: help

  build:
    - podman build -t
        {{.image_name}} .

  runti:
    - podman run --rm -ti
        --name {{.docker_name}}
        {{.image_name}} bash

  execti:
    - podman exec -ti
        {{.docker_name}} bash

  push:
    - podman push {{.image_name}}
