version: '3'

dotenv:
  - .env

includes:
  fw: ./fw.yml

tasks:

  help: task --list-all
  default:
    - task: help

  client:
    - $runner run -d
        --restart always
        --name gost_client
        -e user=$gost_user
        -e pswd=$gost_pswd
        -e kcp_port=$kcp_port
        -e tcp_port=$tcp_port
        -e remote_host=$remote_host
        -e proxy_port=$proxy_port
        -p $proxy_port:$proxy_port
        mooxe/gogost client

  server:
    - $runner run -d
        --restart=always
        --name gost_server
        -e user=$gost_user
        -e pswd=$gost_pswd
        -e kcp_port=$kcp_port
        -e tcp_port=$tcp_port
        -p $kcp_port:$kcp_port/udp
        -p $tcp_port:$tcp_port
        mooxe/gogost server

  log-client:
    - $runner logs -f gost_client

  log-server:
    - $runner logs -f gost_server

  rm-client:
    - $runner rm -f gost_client

  rm-server:
    - $runner rm -f gost_server

  rm-all:
    deps:
      - rm-server
      - rm-client
