version: '3'

dotenv:
  - .env

tasks:

  help: task --list-all
  default:
    - task: help

  client:
    - $runner run -d
        --restart always
        --name gost_client
        -e user=$gost_user
        -e pswd=$gost_pswd
        -e kcp_port=14444
        -e tcp_port=14443
        -e remote_host=$remote_host
        -e proxy_port=1080
        -p 1080:1080
        mooxe/gogost_client

  server:
    - $runner run -d
        --restart=always
        --name gost_server
        -e user=$gost_user
        -e pswd=$gost_pswd
        -e kcp_port=14444
        -e tcp_port=14443
        -p 14444:14444/udp
        -p 14443:14443
        mooxe/gogost_server

  log-client:
    - $runner logs -f gost_client

  log-server:
    - $runner logs -f gost_server

  rm-client:
    - $runner rm -f gost_client

  rm-server:
    - $runner rm -f gost_server
